import Head from 'next/head'
import React from 'react';
import { GetServerSideProps } from 'next';

export const runtime = 'experimental-edge';

function blog({data}:any) {

  return (
    
    <div className ="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
       {data.map((data:any) => (
        
        <div className ="container_conten" key={data.id}>
              <div className ="left">
                <img src={data.image}/>
              </div>

            <div className="right">
                <a href={data.id}> {data.title}</a>
            </div>
            <div className="clear"></div>
        </div>
         
      ))}

    </div>

    
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const res = await fetch('https://newsdailymedia.com/api.php')
    const data  = await res.json()
  return {
    props: { data }
  };
}

export default blog