


import Head from 'next/head'
import React from 'react';
import { GetServerSideProps } from 'next';
import { GraphQLClient, gql } from 'graphql-request';

export const runtime = 'experimental-edge';

function blog({data}:any) {

  return (
    
    <div className ="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      
       {data.posts.nodes.map((data:any) => (
        
        <div className ="container_conten" key={data.uri}>
              <div className ="left">
                <img src={data.featuredImage.node.sourceUrl}/>
              </div>

            <div className="right">
                <a href={data.uri}> {data.title}</a>
            </div>
            <div className="clear"></div>
        </div>
         
      ))}

    </div>

    
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const endpoint = "https://newsdailymedia.com/graphql";
  const graphQLClient = new GraphQLClient(endpoint);


  const query = gql`
  query NewQuery {
    posts {
      nodes {
        title
        uri
        featuredImage {
          node {
            sourceUrl
          }
        }
        
      }
    }
  }
  `
  
const data = await graphQLClient.request(query);



  return {
    props: { data }
  };
}

export default blog

